[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_media_transcode"
version = "0.1.0"
dependencies = [
    "dam"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dam_media_transcode"]

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]