[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_psp"
version = "0.1.0"
description = "A plugin for the DAM system to handle PSP ISOs."
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "AI Agent", email = "ai.agent@example.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

dependencies = [
    "dam",
    "pycdlib",
    "py7zr",
    "patool",
    "zstandard",
    "rarfile",
]

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]
include = ["src/**", "tests/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]
exclude = []
reportDeprecated = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
test = "pytest -n auto"
test-cov = "pytest -n auto --cov=src --cov-report=term-missing --cov-report=xml"
mypy = "mypy --config-file ../../pyproject.toml src tests"