"""Data model for linking entities to model-generated tags."""

from sqlalchemy import Float, ForeignKey, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from ..core import BaseComponent


class ModelGeneratedTagLinkComponent(BaseComponent):
    """
    Links an Entity to a TagConcept, specifically for tags generated by an AI model.

    This component stores the tag suggested by a model, along with the model's name
    and its confidence in that suggestion.
    """

    __tablename__ = "component_model_generated_tag_link"

    entity_id: Mapped[int] = mapped_column(ForeignKey("entities.id", ondelete="CASCADE"), nullable=False, index=True)
    tag_concept_id: Mapped[int] = mapped_column(
        ForeignKey("component_tag_concept.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Name of the model that generated this tag link (e.g., "wd-v1-4-moat-tagger-v2")
    source_model_name: Mapped[str] = mapped_column(String(), nullable=False, index=True)

    # Confidence score from the model for this specific tag suggestion
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Relationships (optional, but can be useful for ORM-level access)
    # entity: Mapped["Entity"] = relationship(back_populates="model_generated_tags")
    # tag_concept: Mapped["TagConceptComponent"] = relationship()

    __table_args__ = (
        UniqueConstraint(
            "entity_id",
            "tag_concept_id",
            "source_model_name",
            name="uq_entity_tag_concept_model",
        ),
    )
