[tool.poe.tasks]
fmt = "ruff format"
format.ref = "fmt"
lint = "ruff check"
fix = "ruff check --fix --unsafe-fixes"
mypy = "mypy --config-file $POE_ROOT/../../pyproject.toml src tests"
pyright = "pyright"
