[tool.poe.tasks]
fmt = "ruff format"
format.ref = "fmt"
lint = "ruff check"
fix = "ruff check --fix --unsafe-fixes"
mypy = "mypy --config-file $POE_ROOT/../../pyproject.toml src tests"
pyright = "pyright"
test = "pytest -n auto --asyncio-mode=debug"
test-cov = "pytest -n auto --cov=src --cov-report=term-missing --cov-report=xml --asyncio-mode=debug"
deptry = "deptry --pep621-dev-dependency-groups dev ."
