[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_test_utils"
version = "0.1.0"
description = "Test utilities for the DAM system."
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "AI Agent", email = "ai.agent@example.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

dependencies = [
    "dam",
    "dam_app",
    "dam_fs",
    "dam_semantic",
    "dam_sire",
    "pytest",
    "pytest-asyncio",
    "psycopg[binary]",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dam_test_utils"]
