from typing import Any

def createParser(filename: str) -> Any: ...

class Metadata:
    def has(self, key: str) -> bool: ...
    def get(self, key: str) -> Any: ...

def extractMetadata(parser: Any) -> Metadata: ...

class config:
    quiet: bool = ...
