[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_source"
version = "0.1.0"
dependencies = [
    "dam",
    "sqlalchemy",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[project.entry-points."dam.plugins"]
dam-source = "dam_source.plugin:SourcePlugin"

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]
include = ["src/**", "tests/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]
exclude = []
reportDeprecated = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
mypy = "mypy --config-file ../../pyproject.toml src tests"