[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_media_image"
version = "0.1.0"
dependencies = [
    "dam",
    "imagehash",
    "Pillow",
    "sqlalchemy",
    "dam_fs",
    "aiofiles",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]
include = ["src/**", "tests/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]
exclude = []
reportDeprecated = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
mypy = "mypy --config-file ../../pyproject.toml src"

[tool.deptry]
known_first_party = ["dam_media_image"]
