[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_sire"
version = "0.1.0"
dependencies = [
    "dam",
    "sire",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dam_sire"]
