[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_sire"
version = "0.1.0"
dependencies = [
    "dam",
    "sire"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "pytest-asyncio",
    "pytest-mock",
]


[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]
include = ["src/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src"]
exclude = []
reportDeprecated = true

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
mypy = "mypy --config-file ../../pyproject.toml src"
