[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_media_audio"
version = "0.1.0"
dependencies = [
    "dam",
    "numpy",
    "dam_test_utils",
    "dam_semantic",
    "dam_sire",
    "sire",
    "sqlalchemy",
    "dam_fs",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]
include = ["src/**", "tests/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]
exclude = []
reportDeprecated = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
markers = [
    "serial",
]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
mypy = "mypy --config-file ../../pyproject.toml src tests"