[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_media_audio"
version = "0.1.0"
dependencies = [
    "dam"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "dam_test_utils",
]

[tool.hatch.build.targets.wheel]
packages = ["src/dam_media_audio"]

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist"]

[tool.poe.tasks]
test = "pytest"