[project]
name = "my_domarkx_project"
version = "0.1.0"
description = "A project created from the domarkx pyproject template."
authors = [
    {name = "Your Name", email = "you@example.com"},
]
requires-python = ">=3.12"
dependencies = [
    "domarkx",
    "ecs_dam_system",
]

[tool.poe.tasks]
run = "domarkx exec-doc session.md"
