[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "domarkx"
version = "0.1.0"
authors = [
    {name = "gameltb", email = "gamegccltb@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "autogen-agentchat",
    "autogen-core",
    "autogen-ext[openai]",
    "libcst",
    "openai",
    "prompt-toolkit",
    "python-dotenv",
    "rich",
    "typer",
    "pyyaml",
]

[project.optional-dependencies]
all = [
    "pytest",
    "typer",
    "libcst",
]
jupyter-executor = [
    "autogen-ext[jupyter-executor]",
]
docker-jupyter-executor = [
    "autogen-ext[docker-jupyter-executor]",
]

[project.scripts]
domarkx = "domarkx.cli:main"

[tool.ruff]
extend = "../../pyproject.toml"
exclude = ["build", "dist", "*.md"]
include = ["src/**", "tests/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]
exclude = []
reportDeprecated = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
asyncio_mode = "auto"

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
test = "pytest -n auto"
test-cov = "pytest -n auto --cov=src --cov-report=term-missing --cov-report=xml"
mypy = "mypy --config-file ../../pyproject.toml src tests"