"""Initial migration

Revision ID: 5c68dcae7595
Revises:
Create Date: 2025-09-09 17:24:29.852847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c68dcae7595'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_owner_page_image', 'page_links', ['owner_entity_id', 'page_image_entity_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_owner_page_image', 'page_links', type_='unique')
    # ### end Alembic commands ###
