[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dam_app"
version = "0.1.0"
description = "A CLI application for the DAM system."
readme = "README.md"
requires-python = ">=3.12"
license = {text = "MIT"}
authors = [
    {name = "AI Agent", email = "ai.agent@example.com"}
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

dependencies = [
    "dam",
    "alembic",
    "python-magic",
    "tqdm",
    "sqlalchemy",
    "typer",
    "dam_fs",
    "dam_source",
    "typing_extensions",
    "rich",
    "dam_archive",
    "dam_sire",
    "sire",
    "aiofiles",
    "tomli",
    "pydantic-settings",
]

[project.optional-dependencies]
image = ["dam_media_image"]
audio = ["dam_media_audio"]
transcode = ["dam_media_transcode"]
psp = ["dam_psp"]
semantic = ["dam_semantic"]
all = [
    "dam_app[image]",
    "dam_app[audio]",
    "dam_app[transcode]",
    "dam_app[psp]",
    "dam_app[semantic]",
]

[project.scripts]
dam-cli = "dam_app.main:app"

[tool.ruff]
extend = "../../pyproject.toml"
exclude = [
    "build",
    "dist",
    "src/dam_app/alembic_template",
]
include = ["src/**", "tests/**"]

[tool.pyright]
extends = "../../pyproject.toml"
include = ["src", "tests"]
exclude = []
reportDeprecated = true
reportUnknownVariableType = "none"
reportUnknownArgumentType = "none"
reportGeneralTypeIssues = "none"

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]
markers = [
    "serial: mark a test as serial",
]

[tool.poe]
include = "../../shared_tasks.toml"

[tool.poe.tasks]
run = "dam-cli"
mypy = "mypy --config-file ../../pyproject.toml src tests"

[tool.deptry.per_rule_ignores]
DEP002 = [
    "dam_media_audio",
    "dam_media_transcode",
    "dam_psp",
    "dam_semantic",
]
